### ISSUE TITLE
Unable to install libqtwebkit4- is libqtwebkit4 necessary?

### ISSUE THREAD

**Issue by realKarthikNair** [l6174/realme_downgrade_guides#2]
As shown in ss, I tried manually installing from repo too 

![image](https://user-images.githubusercontent.com/78267371/204133598-6bedf66a-09c6-4056-8410-3dc638f96917.png)

**Comment by sekiryl** [comment]
No, skip it. I just added it for assurity you can skip it safely.

**Comment by realKarthikNair** [comment]
Thanks
